# Generated by Django 5.1.1 on 2024-09-17 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='subject',
        ),
        migrations.AddField(
            model_name='testresult',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_name',
            field=models.CharField(default='Dummy test', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestSubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('max_marks', models.FloatField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subject')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='dashboard.testresult')),
            ],
        ),
    ]
